In [1]:
x=2

In [2]:
x

2

In [3]:
import numpy as np

In [4]:
b=np.array([1,2,3])
b

array([1, 2, 3])

In [5]:
d=b+2
d

array([3, 4, 5])

In [6]:
e=d-1
e

array([2, 3, 4])

In [7]:
c=np.array([[1,2],[3,4]])
c

array([[1, 2],
       [3, 4]])

In [8]:
f=np.array([[1,2,3],[4,5,6]])
f

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
f.shape

(2, 3)

In [10]:
s=np.array([[1,2,3],[4,5,6],[7,8,9]])
s

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
g=np.array([[[1,2],[3,4]],
            [[5,6],[7,8]]])
g

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [12]:
g.shape #(2, 2, 2)---> 2 layers,2 rows,2 columns

(2, 2, 2)

In [13]:
h=np.array([[[1,2],[3,4]],
             [[5,6],[7,8]],
             [[9,1],[2,3]]])
h

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]],

       [[9, 1],
        [2, 3]]])

In [14]:
h.shape

(3, 2, 2)

In [15]:
i=np.array([[[3,0,0,5],[3,8,1,2]],
            [[1,2,6,2],[2,3,4,5]],
            [[9,0,2,7],[6,8,5,3]]])
i

array([[[3, 0, 0, 5],
        [3, 8, 1, 2]],

       [[1, 2, 6, 2],
        [2, 3, 4, 5]],

       [[9, 0, 2, 7],
        [6, 8, 5, 3]]])

In [16]:
i.shape #to check shape of array

(3, 2, 4)

In [17]:
i.ndim #for checking the dimension of array

3

In [18]:
i.size #to check the no of elements in array

24

In [19]:
i.dtype #to check the datatype of array

dtype('int32')

In [20]:
i.astype('float') #changes the datatype of an array

array([[[3., 0., 0., 5.],
        [3., 8., 1., 2.]],

       [[1., 2., 6., 2.],
        [2., 3., 4., 5.]],

       [[9., 0., 2., 7.],
        [6., 8., 5., 3.]]])

In [21]:
i.astype(int)

array([[[3, 0, 0, 5],
        [3, 8, 1, 2]],

       [[1, 2, 6, 2],
        [2, 3, 4, 5]],

       [[9, 0, 2, 7],
        [6, 8, 5, 3]]])

In [22]:
np.ones(3)

array([1., 1., 1.])

In [23]:
np.ones(5,dtype='int')

array([1, 1, 1, 1, 1])

In [24]:
np.zeros(4)

array([0., 0., 0., 0.])

In [25]:
np.zeros(4,dtype='int')

array([0, 0, 0, 0])

In [26]:
np.random.random(3)

array([0.22742664, 0.54209453, 0.30846157])

In [27]:
np.random.randint(0,5,size=(2,3)) #0,5 is range, size=(2,3) is 2 layer 3 rows

array([[4, 2, 1],
       [3, 2, 0]])

In [28]:
t=np.random.randint(20,30,size=(2,3,4)) #size=(2,3,4) 2 layers 3 rows 4 columns
t

array([[[20, 20, 25, 24],
        [28, 26, 21, 26],
        [27, 29, 22, 27]],

       [[25, 25, 25, 20],
        [29, 22, 29, 29],
        [28, 25, 24, 28]]])

In [29]:
np.full((2,2),6) #(2,2) 2 rows and 2 columns which are filled with 6 

array([[6, 6],
       [6, 6]])

In [78]:
np.full((2,3,4),9)

array([[[9, 9, 9, 9],
        [9, 9, 9, 9],
        [9, 9, 9, 9]],

       [[9, 9, 9, 9],
        [9, 9, 9, 9],
        [9, 9, 9, 9]]])

In [31]:
np.identity(3) #given an identity matrix in which the diagonal element will be 1 rest all will be zero by default it is float 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
np.identity(4,dtype='int')

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [33]:
#to get the number of evenly spaced values between intervals
#parameters for the function -np.linspace(start,stop,num,endpoint,retstep,dtype)
#dtype is the output array
np.linspace(10,20,9,dtype='int')

array([10, 11, 12, 13, 15, 16, 17, 18, 20])

In [34]:
np.linspace(10,20,8,endpoint=False,retstep=True,dtype='int')

(array([10, 11, 12, 13, 15, 16, 17, 18]), 1.25)

In [35]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [37]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [38]:
#indexing and slicing
b=np.arange(10,20)
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [39]:
b[:]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [40]:
b[0:2]

array([10, 11])

In [41]:
b[6:]

array([16, 17, 18, 19])

In [42]:
b[2:3]

array([12])

In [43]:
b[:8]

array([10, 11, 12, 13, 14, 15, 16, 17])

In [44]:
d=np.array([[1,2],[3,4],[5,6]])
d

array([[1, 2],
       [3, 4],
       [5, 6]])

In [45]:
d[1:3,1:3]

array([[4],
       [6]])

In [46]:
d[2,0]

5

In [47]:
d[1:3]

array([[3, 4],
       [5, 6]])

In [48]:
d[0:2,1]

array([2, 4])

In [49]:
d[2,0:1]

array([5])

In [50]:
d[1,1]

4

In [51]:
#task
n=np.array([[2,3,4,5,6],
            [8,2,3,10,11],
            [15,14,1,9,20],
            [25,24,12,16,26]])
n

array([[ 2,  3,  4,  5,  6],
       [ 8,  2,  3, 10, 11],
       [15, 14,  1,  9, 20],
       [25, 24, 12, 16, 26]])

In [52]:
n[3:5]

array([[25, 24, 12, 16, 26]])

In [53]:
n[2:6]

array([[15, 14,  1,  9, 20],
       [25, 24, 12, 16, 26]])

In [54]:
n[2:,3:]

array([[ 9, 20],
       [16, 26]])

In [55]:
n[2:,1:4]

array([[14,  1,  9],
       [24, 12, 16]])

In [56]:
n[1:3,1:3]

array([[ 2,  3],
       [14,  1]])

In [57]:
n[1:3,0:2]

array([[ 8,  2],
       [15, 14]])

In [58]:
n[0:3,3:]

array([[ 5,  6],
       [10, 11],
       [ 9, 20]])

In [59]:
n[0:2,1:4]

array([[ 3,  4,  5],
       [ 2,  3, 10]])

In [60]:
n[1:3,1:4]

array([[ 2,  3, 10],
       [14,  1,  9]])

In [61]:
t=np.random.randint(10,20,size=(3,2,4))
t

array([[[15, 10, 14, 16],
        [16, 18, 15, 18]],

       [[10, 17, 14, 12],
        [11, 17, 16, 16]],

       [[17, 18, 19, 12],
        [12, 14, 12, 19]]])

In [62]:
t[1:]

array([[[10, 17, 14, 12],
        [11, 17, 16, 16]],

       [[17, 18, 19, 12],
        [12, 14, 12, 19]]])

In [63]:
t[1:,0:1]

array([[[10, 17, 14, 12]],

       [[17, 18, 19, 12]]])

In [64]:
t[1:,0:1,3:]

array([[[12]],

       [[12]]])

In [65]:
t[0:2,1:2,1:2]

array([[[18]],

       [[17]]])

In [66]:
n=np.array([[[19,4,19,12],[15,17,6,12]],
            [[4,7,16,7],[15,8,6,14]],
            [[3,13,12,2],[17,5,18,14]]])
n

array([[[19,  4, 19, 12],
        [15, 17,  6, 12]],

       [[ 4,  7, 16,  7],
        [15,  8,  6, 14]],

       [[ 3, 13, 12,  2],
        [17,  5, 18, 14]]])

In [67]:
n[0:,0:1,0]

array([[19],
       [ 4],
       [ 3]])

In [68]:
n[0:2,0:,2:3]

array([[[19],
        [ 6]],

       [[16],
        [ 6]]])

In [69]:
n[0:2,0:,2]

array([[19,  6],
       [16,  6]])

In [70]:
n[1:,0:,1:3]

array([[[ 7, 16],
        [ 8,  6]],

       [[13, 12],
        [ 5, 18]]])

In [71]:
n[1:,1:,1:3]

array([[[ 8,  6]],

       [[ 5, 18]]])

In [72]:
n[0:2,0:1,1:]

array([[[ 4, 19, 12]],

       [[ 7, 16,  7]]])

In [73]:
o=np.random.randint(1,20,size=(3,2))
o

array([[ 8, 12],
       [12,  8],
       [ 6, 15]])

In [74]:
np.transpose(o)

array([[ 8, 12,  6],
       [12,  8, 15]])

In [75]:
m=np.random.randint(1,20,size=(8))
m

array([ 2,  3,  7, 14, 13, 13, 16,  9])

In [76]:
m.reshape(2,4)

array([[ 2,  3,  7, 14],
       [13, 13, 16,  9]])

In [77]:
m.reshape(2,4)

array([[ 2,  3,  7, 14],
       [13, 13, 16,  9]])